import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import style from '../styles/canvas.module.css'
import sampleImg from 'public/default-spatial-room-bg.png'

const Home: NextPage = () => {
  const [ctx, setCtx] = useState<CanvasRenderingContext2D | null>(null)
  const [loaded, setLoaded] = useState(false)

  // useEffect(() => {
  //   const canvas: HTMLCanvasElement | null = document.getElementById('canvas') as HTMLCanvasElement
  //   canvas.height = innerHeight
  //   canvas.width = innerWidth
  //   const canvasContext = canvas?.getContext('2d')
  //   if (canvasContext !== null) {
  //     setCtx(canvasContext)
  //   }
  // }, [])

  // 状態にコンテキストが登録されたらそれに対して操作できる
  useEffect(() => {
    if (ctx !== null) {
      const img = new Image()
      img.src = sampleImg.src
      img.onload = () => {
        // 更にこれに続いて何か処理をしたい場合
        ctx.drawImage(img, 0, 0)
        setLoaded(true)
      }
    }
  }, [ctx])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={style.outline}>
        <div className={style.overlay}>
          <div className={style.view}></div>
          {/* <canvas id={'canvas'}>Hello World</canvas> */}
        </div>
      </div>
    </div>
  )
}

export default Home
